# -*- coding: utf-8 -*-
"""Spark_Reading_Streaming_Examples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ClD1OD7hnAAhUGOO7xbNzjly8BUoM5g2

# **Install the libraries**
"""

!pip install pyspark
!pip install -U -q PyDrive
!apt install openjdk-8-jdk-headless -qq
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"

"""# **Create a session**"""

from pyspark.sql import SparkSession
from pyspark.sql.types import StringType

spark_session = SparkSession \
  .builder \
  .appName("spark_reading_streaming") \
  .master("yarn").getOrCreate()

project_number = 823002731253
location = "us-central1-a"
topic_id = "log-messages-topic"
subscription_id = "log-messages-subscription"

"""# **Reading From Pub/Sub - Spark Streaming**"""

dataframe = (
    spark_session.readStream.format("pubsublite")
    .option(
        "pubsublite.subscription",
        f"projects/{project_number}/locations/{location}/subscriptions/{subscription_id}",
    )
    .load()
)

dataframe = dataframe.withColumn("data", dataframe.data.cast(StringType()))

query = (
    dataframe.writeStream.format("console")
    .outputMode("append")
    .trigger(processingTime="1 second")
    .start()
)

query.awaitTermination(120)
query.stop()